# Lab 4: LDA and QDA from Scratch
## by Tiffany Nguyen
The purpose to this lab is to code a Linear Discriminant Analysis and Quadratic Discriminant Analysis model to classify data from the Iris dataset without using a machine learning library
## Part 1: Parsing and Dividing Data

In [102]:
import numpy as np

In [103]:
# Read all data
allData = np.empty((0, 5))
with open("iris.txt", "r") as filestream:
  for line in filestream:
    currentline = line.strip().split(",")
    allData = np.append(allData, [np.array([float(currentline[0]), float(currentline[1]), float(currentline[2]), float(currentline[3]), currentline[4]], dtype=object)], axis=0)
print(allData)

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-setosa']
 [4.8 3.1 

In [104]:
# separate data by category
irisSetosaData = allData[0:50]
irisVersicolorData = allData[50:100]
irisVirginicaData = allData[100:150]
# print(irisVirginicaData)

In [105]:
# Break into training and testing dataset (80% train, 20% test)
irisSetosaTrain = irisSetosaData[0:40]
irisSetosaTest = irisSetosaData[40:50]
irisVersicolorTrain = irisVersicolorData[0:40]
irisVersicolorTest = irisVersicolorData[40:50]
irisVirginicaTrain = irisVirginicaData[0:40]
irisVirginicaTest = irisVirginicaData[40:50]

## Part 2: Build QDA Classifier
### Training

In [106]:
print("iris setosa")

# calculate N
irisSetosaN = len(irisSetosaTrain)
print("N:", irisSetosaN)

#calculate mu (average)
irisSetosaMu = np.mean(irisSetosaTrain[:, 0:4], axis=0)
print("Mu:", irisSetosaMu)

# calculate covariance
irisSetosaCovariance = np.dot(np.transpose(np.subtract(irisSetosaTrain[:, 0:4], irisSetosaMu)), np.subtract(irisSetosaTrain[:, 0:4], irisSetosaMu)) / irisSetosaN
print("Covariance:\n", irisSetosaCovariance)
print("Covariance shape:", irisSetosaCovariance.shape)

iris setosa
N: 40
Mu: [5.0375 3.4400000000000004 1.4625 0.23249999999999993]
Covariance:
 [[0.12784374999999998 0.09649999999999997 0.012656249999999997
  0.013281249999999994]
 [0.09649999999999997 0.12939999999999996 0.0019999999999999896
  0.014199999999999996]
 [0.012656249999999997 0.0019999999999999896 0.02884375000000001
  0.004468749999999998]
 [0.013281249999999994 0.014199999999999996 0.004468749999999998
  0.00969375]]
Covariance shape: (4, 4)


In [107]:
print("iris Versicolor")

# calculate N
irisVersicolorN = len(irisSetosaTrain)
print("N:", irisVersicolorN)

#calculate mu (average)
irisVersicolorMu = np.mean(irisVersicolorTrain[:, 0:4], axis=0)
print("Mu:", irisVersicolorMu)

# calculate covariance
irisVersicolorCovariance = np.dot(np.transpose(np.subtract(irisVersicolorTrain[:, 0:4], irisVersicolorMu)), np.subtract(irisVersicolorTrain[:, 0:4], irisVersicolorMu)) / irisVersicolorN
print("Covariance:\n", irisVersicolorCovariance)

iris Versicolor
N: 40
Mu: [6.01 2.7800000000000007 4.3175 1.35]
Covariance:
 [[0.26689999999999997 0.08444999999999997 0.16782500000000003
  0.05099999999999999]
 [0.08444999999999997 0.1081 0.07885 0.04425]
 [0.16782500000000003 0.07885 0.19844375000000003 0.071875]
 [0.05099999999999999 0.04425 0.071875 0.04199999999999999]]


In [108]:
print("iris Virginica")

# calculate N
irisVirginicaN = len(irisVirginicaTrain)
print("N:", irisVirginicaN)

#calculate mu (average)
irisVirginicaMu = np.mean(irisVirginicaTrain[:, 0:4], axis=0)
print("Mu:", irisVirginicaMu)

# calculate covariance
irisVirginicaCovariance = np.dot(np.transpose(np.subtract(irisVirginicaTrain[:, 0:4], irisVirginicaMu)), np.subtract(irisVirginicaTrain[:, 0:4], irisVirginicaMu)) / irisVirginicaN
print("Covariance:\n", irisVirginicaCovariance)

iris Virginica
N: 40
Mu: [6.6225 2.9599999999999995 5.6075 1.9899999999999995]
Covariance:
 [[0.4562437500000002 0.10764999999999998 0.3488312500000001
  0.049975000000000006]
 [0.10764999999999998 0.11039999999999997 0.07904999999999998
  0.04510000000000001]
 [0.3488312500000001 0.07904999999999998 0.3366937499999999 0.057825]
 [0.049975000000000006 0.04510000000000001 0.057825 0.07239999999999999]]


### Prediction

In [109]:
def irisSetosaProb(testX):
  numOfFeatures = 4
  irisSetosaFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(irisSetosaCovariance.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisSetosaMu
  inverseCovariance = np.linalg.inv(irisSetosaCovariance.astype(np.float64))
  irisSetosaProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisSetosaFrac * irisSetosaProb
print(irisSetosaProb(np.array([5.1,3.5,1.4,0.2])))

def irisVersicolorProb(testX):
  numOfFeatures = 4
  irisVersicolorFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(irisVersicolorCovariance.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisVersicolorMu
  inverseCovariance = np.linalg.inv(irisVersicolorCovariance.astype(np.float64))
  irisVersicolorProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisVersicolorFrac * irisVersicolorProb
print(irisVersicolorProb(np.array([5.1,3.5,1.4,0.2])))

def irisVirginicaProb(testX):
  numOfFeatures = 4
  irisVirginicaFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(irisVirginicaCovariance.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisVirginicaMu
  inverseCovariance = np.linalg.inv(irisVirginicaCovariance.astype(np.float64))
  irisVirginicaProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisVirginicaFrac * irisVirginicaProb
print(irisVirginicaProb(np.array([5.1,3.5,1.4,0.2])))


17.928310515542087
6.027533545975077e-24
5.761874894530037e-37


In [110]:
def predictionQDA(curData):
  irisSetosaP = irisSetosaProb(curData[0:4])
  irisVersicolorP = irisVersicolorProb(curData[0:4])
  irisVirginicaP = irisVirginicaProb(curData[0:4])
  return np.argmax([irisSetosaP, irisVersicolorP, irisVirginicaP])

In [111]:
# Test QDA on test data:
allTestData = np.append(np.append(irisSetosaTest, irisVersicolorTest, axis=0),irisVirginicaTest, axis=0)
# print(allTest)

testCorrectQDA = 0
testIncorrectQDA = 0

for curRow in allTestData:
  predictionIndex = predictionQDA(curRow)
  if predictionIndex == 0 and curRow[4] == "Iris-setosa":
    testCorrectQDA+=1
  elif predictionIndex == 1 and curRow[4] == "Iris-versicolor":
    testCorrectQDA+=1
  elif predictionIndex == 2 and curRow[4] == "Iris-virginica":
    testCorrectQDA+=1
  else:
    testIncorrectQDA+=1

print("correct:", testCorrectQDA)
print("incorrect:", testIncorrectQDA)
print("accuracy on test data:", testCorrectQDA / (testCorrectQDA +testIncorrectQDA))

correct: 30
incorrect: 0
accuracy on test data: 1.0


In [112]:
# Test QDA on train data:
allTrainData = np.append(np.append(irisSetosaTrain, irisVersicolorTrain, axis=0),irisVirginicaTrain, axis=0)
# print(allTest)

trainCorrectQDA = 0
trainIncorrectQDA = 0

for curRow in allTrainData:
  predictionIndex = predictionQDA(curRow)
  if predictionIndex == 0 and curRow[4] == "Iris-setosa":
    trainCorrectQDA+=1
  elif predictionIndex == 1 and curRow[4] == "Iris-versicolor":
    trainCorrectQDA+=1
  elif predictionIndex == 2 and curRow[4] == "Iris-virginica":
    trainCorrectQDA+=1
  else:
    trainIncorrectQDA+=1

print("correct:", trainCorrectQDA)
print("incorrect:", trainIncorrectQDA)
print("accuracy on train data:", round((trainCorrectQDA / (trainCorrectQDA +trainIncorrectQDA)), 2))

correct: 118
incorrect: 2
accuracy on train data: 0.98


## Part 3: Build LDA Classifier

In [113]:
avgCovariance = (irisSetosaCovariance + irisVersicolorCovariance + irisVirginicaCovariance)/3
print(avgCovariance)

[[0.2836625000000001 0.09619999999999997 0.17643750000000002
  0.03808541666666666]
 [0.09619999999999997 0.11596666666666665 0.05329999999999999
  0.03451666666666667]
 [0.17643750000000002 0.05329999999999999 0.18799374999999996
  0.04472291666666667]
 [0.03808541666666666 0.03451666666666667 0.04472291666666667
  0.04136458333333332]]


In [114]:
def irisSetosaProbLDA(testX):
  numOfFeatures = 4
  irisSetosaFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(avgCovariance.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisSetosaMu
  inverseCovariance = np.linalg.inv(avgCovariance.astype(np.float64))
  irisSetosaProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisSetosaFrac * irisSetosaProb
print(irisSetosaProbLDA(np.array([5.1,3.5,1.4,0.2])))

def irisVersicolorProbLDA(testX):
  numOfFeatures = 4
  irisVersicolorFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(avgCovariance.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisVersicolorMu
  inverseCovariance = np.linalg.inv(avgCovariance.astype(np.float64))
  irisVersicolorProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisVersicolorFrac * irisVersicolorProb
print(irisVersicolorProbLDA(np.array([5.1,3.5,1.4,0.2])))

def irisVirginicaProbLDA(testX):
  numOfFeatures = 4
  irisVirginicaFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(avgCovariance.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisVirginicaMu
  inverseCovariance = np.linalg.inv(avgCovariance.astype(np.float64))
  irisVirginicaProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisVirginicaFrac * irisVirginicaProb
print(irisVirginicaProbLDA(np.array([5.1,3.5,1.4,0.2])))


3.4908948282495755
1.551973687975383e-21
7.334054045056142e-41


In [115]:
def predictionLDA(curData):
  irisSetosaP = irisSetosaProbLDA(curData[0:4])
  irisVersicolorP = irisVersicolorProbLDA(curData[0:4])
  irisVirginicaP = irisVirginicaProbLDA(curData[0:4])
  return np.argmax([irisSetosaP, irisVersicolorP, irisVirginicaP])

In [116]:
# Test LDA on test data:
testCorrectLDA = 0
testIncorrecLDA = 0

for curRow in allTestData:
  predictionIndex = predictionLDA(curRow)
  if predictionIndex == 0 and curRow[4] == "Iris-setosa":
    testCorrectLDA+=1
  elif predictionIndex == 1 and curRow[4] == "Iris-versicolor":
    testCorrectLDA+=1
  elif predictionIndex == 2 and curRow[4] == "Iris-virginica":
    testCorrectLDA+=1
  else:
    testIncorrecLDA+=1

print("correct:", testCorrectLDA)
print("incorrect:", testIncorrecLDA)
print("accuracy on test data:", testCorrectLDA / (testCorrectLDA +testIncorrecLDA))

correct: 30
incorrect: 0
accuracy on test data: 1.0


In [117]:
# Test LDA on train data:
trainCorrectLDA = 0
trainIncorrectLDA = 0

for curRow in allTrainData:
  predictionIndex = predictionLDA(curRow)
  if predictionIndex == 0 and curRow[4] == "Iris-setosa":
    trainCorrectLDA+=1
  elif predictionIndex == 1 and curRow[4] == "Iris-versicolor":
    trainCorrectLDA+=1
  elif predictionIndex == 2 and curRow[4] == "Iris-virginica":
    trainCorrectLDA+=1
  else:
    trainIncorrectLDA+=1

print("correct:", trainCorrectLDA)
print("incorrect:", trainIncorrectLDA)
print("accuracy on train data:", round((trainCorrectLDA / (trainCorrectLDA +trainIncorrectLDA)), 3))

correct: 117
incorrect: 3
accuracy on train data: 0.975


## Part 4: Linearly Separable Class
**Conclusion**: Yes, Iris Setosa is linearly separable from the other classes because there is a 100% accuracy when doing binary classification to determine if a given sample is iris setosa
### Test Iris-setosa

In [118]:
def isIrisSetosa(curData):
  return predictionLDA(curData) == 0

In [120]:
# Test isIrisSetosa on all data:
testCorrectIrisSetosa= 0
testIncorrectIrisSetosa = 0

for curRow in allData:
  if(isIrisSetosa(curRow) == (curRow[4] == "Iris-setosa")):
    testCorrectIrisSetosa += 1
  else:
    testIncorrectIrisSetosa += 1

print("correct:", testCorrectIrisSetosa)
print("incorrect:", testIncorrectIrisSetosa)
print("accuracy for isIrisSetosa:", testCorrectIrisSetosa / (testCorrectIrisSetosa +testIncorrectIrisSetosa))

correct: 150
incorrect: 0
accuracy for isIrisSetosa: 1.0


### Test Iris Versicolor

In [121]:
def isIrisVersicolor(curData):
  return predictionLDA(curData) == 1

In [122]:
# Test isIrisSetosa on all data:
testCorrectIrisVersicolor= 0
testIncorrectIrisVersicolor = 0

for curRow in allData:
  if(isIrisVersicolor(curRow) == (curRow[4] == "Iris-versicolor")):
    testCorrectIrisVersicolor += 1
  else:
    testIncorrectIrisVersicolor += 1

print("correct:", testCorrectIrisVersicolor)
print("incorrect:", testIncorrectIrisVersicolor)
print("accuracy on isIrisVersicolor:", testCorrectIrisVersicolor / (testCorrectIrisVersicolor +testIncorrectIrisVersicolor))

correct: 147
incorrect: 3
accuracy on isIrisVersicolor: 0.98


### Test Iris Virginica

In [123]:
def isIrisVirginica(curData):
  return predictionLDA(curData) == 2

In [124]:
# Test isIrisVirginica on all data:
testCorrectIrisVirginica= 0
testIncorrectIrisVirginica = 0

for curRow in allData:
  if(isIrisVirginica(curRow) == (curRow[4] == "Iris-virginica")):
    testCorrectIrisVirginica += 1
  else:
    testIncorrectIrisVirginica += 1

print("correct:", testCorrectIrisVirginica)
print("incorrect:", testIncorrectIrisVirginica)
print("accuracy on isIrisVersicolor:", testCorrectIrisVirginica / (testCorrectIrisVirginica +testIncorrectIrisVirginica))

correct: 147
incorrect: 3
accuracy on isIrisVersicolor: 0.98


## Part 5: Assume Features are Independent
**Conclusion**: While the time for training are pretty similar, the time to train when the features are independent is normally slightly shorter than when the featues are dependent, telling us that using a diagonal matrix for covariance makes the calculations faster

In [92]:
import time

In [125]:
# Turn Covariance into a diagonal matrix because features are independent
irisSetosaCovarianceDiagonal = np.diag(np.diag(irisSetosaCovariance))
print(irisSetosaCovarianceDiagonal)
irisVersicolorCovarianceDiagonal = np.diag(np.diag(irisVersicolorCovariance))
print(irisVersicolorCovarianceDiagonal)
irisVirginicaCovarianceDiagonal = np.diag(np.diag(irisVirginicaCovariance))
print(irisVersicolorCovarianceDiagonal)

[[0.12784374999999998 0 0 0]
 [0 0.12939999999999996 0 0]
 [0 0 0.02884375000000001 0]
 [0 0 0 0.00969375]]
[[0.26689999999999997 0 0 0]
 [0 0.1081 0 0]
 [0 0 0.19844375000000003 0]
 [0 0 0 0.04199999999999999]]
[[0.26689999999999997 0 0 0]
 [0 0.1081 0 0]
 [0 0 0.19844375000000003 0]
 [0 0 0 0.04199999999999999]]


In [126]:
def irisSetosaProbIndependent(testX):
  numOfFeatures = 4
  irisSetosaFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(irisSetosaCovarianceDiagonal.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisSetosaMu
  irisSetosaCovarianceDiagonalInverse = np.linalg.inv(irisSetosaCovarianceDiagonal.astype(np.float64))
  irisSetosaProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), irisSetosaCovarianceDiagonalInverse),(xMinusMu)))
  return irisSetosaFrac * irisSetosaProb
print(irisSetosaProb(np.array([5.1,3.5,1.4,0.2])))

def irisVersicolorProbIndependent(testX):
  numOfFeatures = 4
  irisVersicolorFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(irisVersicolorCovarianceDiagonal.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisVersicolorMu
  inverseCovariance = np.linalg.inv(irisVersicolorCovarianceDiagonal.astype(np.float64))
  irisVersicolorProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisVersicolorFrac * irisVersicolorProb
print(irisVersicolorProb(np.array([5.1,3.5,1.4,0.2])))

def irisVirginicaProbIndependent(testX):
  numOfFeatures = 4
  irisVirginicaFrac = 1/(((2*np.pi)**(numOfFeatures/2))*(np.linalg.det(irisVirginicaCovarianceDiagonal.astype(np.float64))**(1/2)))
  xMinusMu = testX-irisVirginicaMu
  inverseCovariance = np.linalg.inv(irisVirginicaCovarianceDiagonal.astype(np.float64))
  irisVirginicaProb = np.e**(-1/2* np.dot(np.dot(np.transpose(xMinusMu), inverseCovariance),(xMinusMu)))
  return irisVirginicaFrac * irisVirginicaProb
print(irisVirginicaProb(np.array([5.1,3.5,1.4,0.2])))

17.928310515542087
6.027533545975077e-24
5.761874894530037e-37


In [127]:
def predictionQDAIndependent(curData):
  irisSetosaP = irisSetosaProbIndependent(curData[0:4])
  irisVersicolorP = irisVersicolorProbIndependent(curData[0:4])
  irisVirginicaP = irisVirginicaProbIndependent(curData[0:4])
  return np.argmax([irisSetosaP, irisVersicolorP, irisVirginicaP])

In [131]:
# Run and time normal QDA on all data
independentStartTime = time.time()
trainCorrectQDAInd = 0
trainIncorrectQDAInd = 0

for curRow in allTrainData:
  predictionIndex = predictionQDAIndependent(curRow)
  if predictionIndex == 0 and curRow[4] == "Iris-setosa":
    trainCorrectQDAInd+=1
  elif predictionIndex == 1 and curRow[4] == "Iris-versicolor":
    trainCorrectQDAInd+=1
  elif predictionIndex == 2 and curRow[4] == "Iris-virginica":
    trainCorrectQDAInd+=1
  else:
    trainIncorrectQDAInd+=1
  
dependentTime = time.time() - independentStartTime
print("Time for independent QDA:", dependentTime)

print("correct:", trainCorrectQDAInd)
print("incorrect:", trainIncorrectQDAInd)
print("accuracy on all data:", round((trainCorrectQDAInd / (trainCorrectQDAInd +trainIncorrectQDAInd)), 2))

Time for independent QDA: 0.0065441131591796875
correct: 115
incorrect: 5
accuracy on all data: 0.96


In [129]:
# Run and time normal QDA on all data
dependentStartTime = time.time()
trainCorrectQDA = 0
trainIncorrectQDA = 0

for curRow in allTrainData:
  predictionIndex = predictionQDA(curRow)
  if predictionIndex == 0 and curRow[4] == "Iris-setosa":
    trainCorrectQDA+=1
  elif predictionIndex == 1 and curRow[4] == "Iris-versicolor":
    trainCorrectQDA+=1
  elif predictionIndex == 2 and curRow[4] == "Iris-virginica":
    trainCorrectQDA+=1
  else:
    trainIncorrectQDA+=1
  
dependentTime = time.time() - dependentStartTime
print("Time for dependent QDA:", dependentTime)

print("correct:", trainCorrectQDA)
print("incorrect:", trainIncorrectQDA)
print("accuracy on all data:", round((trainCorrectQDA / (trainCorrectQDA +trainIncorrectQDA)), 2))

Time for dependent QDA: 0.009326934814453125
correct: 118
incorrect: 2
accuracy on all data: 0.98
